before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: N9ckPStSQfoc9wrOzd9XnZui0US/u6n0jedDa1SCiYOrO7OwWLn1wFSPpNAT7aDOMQmQX9ZfTdB1ymk1SBgQniJMiZPS7PMUosznlHxXPJg9iq6NokeQuRgliJXl/t4eW4cmzpDW1EJScnq9YuG47JzneoclKrYNQKtTA/kbjC55CXij92wsIU4LCygOfpMVymy58nLOA6FY6bqC2Gh2+AEQ1JA7SSgnRvxiFUQeUn3vc3SQ8snx60CZ80+q/D/VHWy/H24R9K9P8t8r0VV+bXKivYszW3CbITcZvY/Xb1zDCc4Vo/k+NRZCN/9jLjKYAO7trjw0oWoeTc0c6IhZQoXTztbZOnQMfomLwAnI4PZdbFT6KSdUb0Fidzgn515iQdbW/fGUgkHeQUhJ0JrEtvRIPSpeBw+R98uBG4B85Bz3P/dkzgshunbEp71g5d2TcsxglM8dVw1AfOO936W2DIunFz2Ldw0oxQWywqZxQ166MpquSvEupHdOLwrc6NCp95MowURK0PTihMMNcsCzPHk/FDOcX386yRGkSo03kArNeVXGrSjfl3GQ9jag/OF2IPMGvgGYnCtSwlXbFjf63wsJzPghsRWzwlooPNmDSKrHpA76Lma8faZsjjbhVUxocjk+8vrpUc5bbHqcUbPG37MIMGLwdfzFNcwKk7DcTMc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
